name: CI

on:
  push:
    branches: [ master ]
    # branches: [ develop ]
jobs:
  test-job:
    runs-on: ubuntu-latest
    container:
      image: mcublog/embedded_gcc_cmake:latest
    steps:
      - uses: actions/checkout@v3
      - name: Cmake version
        run: cmake --version
      - name: GCC version
        run: gcc --version
      - name: Configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=arm-none-eabi-gcc ..
      - name: Build and Run Tests
        run: cd build && make all && ctest --output-junit results.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'build/*.xml'

  build-job:
    needs: test-job
    runs-on: ubuntu-latest
    container:
      image: mcublog/embedded_gcc_cmake:latest
      volumes:
        - build:/build
    steps:
      - uses: actions/checkout@v3
      - name: ARM GCC version
        run: arm-none-eabi-gcc --version
      - name: Configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=arm-none-eabi-gcc ..
      - name: Build and Run Tests
        run: cd build && make all
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlt-sandbox
          path: |
            build/targets/stm32l0xx/sandbox_fw
